import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import { cn } from '@/lib/utils/cn';
import { Navbar } from '@/components/Navbar';
import TrpcProvider from '@/components/Trpc-provider';
import 'react-loading-skeleton/dist/skeleton.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='light'>
      <body
        className={cn(
          'min-h-screen antialiased font-sans grainy',
          inter.className,
        )}>
        <TrpcProvider>
          <Navbar />
          {children}
        </TrpcProvider>
      </body>
    </html>
  );
}
